### ISSUE TITLE
这个只能纯命令行部署么，有没有可视化部署

### ISSUE THREAD

**Issue by lopins** [admpub/webx#3]

**Comment by admpub** [comment]
是的，只能命令行运行。在正式环境中一般配合 Nging 中的 进程值守 或 supervisor 来启动

**Comment by admpub** [comment]
> 是的，只能命令行运行。在正式环境中一般配合 Nging 中的 进程值守 或 supervisor 来启动

或者安装为服务 `./可执行文件 service install` 例如：`./webx service install`，或者指定监听端口 `./webx service install -p 18080`

**Comment by lopins** [comment]
> > 是的，只能命令行运行。在正式环境中一般配合 Nging 中的 进程值守 或 supervisor 来启动
> 
> 或者安装为服务 `./可执行文件 service install` 
> 例如：
> ```
> ./webx service install
> ```
> 或者指定监听端口 
> ```
> ./webx service install -p 18080
> ```

直接打包一下，x86平台单文件打包

**Comment by admpub** [comment]
@lopins 已经发布可执行文件：https://github.com/admpub/webx/releases

**Comment by lopins** [comment]
> @lopins 已经发布可执行文件：https://github.com/admpub/webx/releases

好的
